language: node_js     
node_js:
- stable
branches:
  only:
  - master
before_script:
- npm install -g bower
- npm install gulp
- bower install
script: 
- git config user.email "travis@mutualab.org";git config user.name "Travis deployment"
- git remote set-url origin https://${GH_TOKEN}@${GH_REF}
- git remote set-branches --add origin gh-pages
- git fetch --all 
- gulp build:gh-pages
cache:
  directories:
  - node_modules
  - bower_components
env:
  global:
  - GH_REF: github.com/Mutualab/mutualab.org
  - GH_TOKEN: KESErWK7tio/+VIvmfPXH7IkD3/FYStgtFOTTEWvlgVCebMdDvsLyXpHL2LHH0Z0A0iivPTvNvYUigAC7G9vo75BCu70BVjsbN4M9tI2WTOy9bEeu/dIgu+DkU0LUQ+UO4gN8PQmVwL1BURYmSnTsitC7nqqOQKmg2anuPLDqNONyDP3iaZV6YKOyl440PEjSyB0YGW9b4SYyufTLDThrXV6fYTDi9RCZO6qejehKvc6cC0IZo8nTWfLd3NISwNSw87jrcAX1BBIJd3AqQRulm9oEpGe/xAf52b+1LGahRlD6Dqi+2KvOIYp5mCrzSNdtSEs20PfzgvyG+vElRa5nYYUN821i9DyjV4G0ftuLLU6karUDrektGPi+/BwOyyYMcaifZ+No2t9ulg7VG/uivQQy7tEPcspuKLgS6Xy8Pb7aT7MqQ27kducTYXprL+CJ0rtXHC+dizo6PHpdAhsjl6NQczJs9735bhoVAPVrstXh/FvHdChwU9qWXvHoYLWuJxX1NiyKiTAI2JIHXAkjJLuT1DSYWEUL7mr11Nm/UYWvcyEvbid6JCGZql1zqw3aD3tI3PP0mVh19np14mGyGh+kIz0ndD8XBW62KNG8vDYHAH8Aj9ly3b3dceGCEaOz2JqPLxNeOTyCUFEW4VOTy97m9HgBV4ZoWkeM3mBvCY=
  
