language: node_js     
node_js:
- stable
branches:
  only:
  - master
before_script:
- npm install -g bower
- npm install gulp
- bower install
script: git --version
cache:
  directories:
  - node_modules
  - bower_components
  
