language: node_js     
node_js:
- stable
branches:
  only:
  - master
before_script:
- npm install -g bower
- npm install gulp
- bower install
script: git fetch origin gh-pages; git checkout -b gh-pages origin/master; git checkout master;
cache:
  directories:
  - node_modules
  - bower_components
  
