language: node_js     
node_js:
- stable
branches:
  only:
  - master
before_script:
- npm install -g bower
- npm install gulp
- npm install
- bower install
script: git fetch origin gh-pages; gulp build:gh-pages
cache:
- node_modules
- bower_components
  
