language: node_js     
node_js:
- stable
branches:
  only:
  - master
before_script:
- npm install -g bower
- npm install gulp
- bower install
script: 
- git config --global user.email "travis@deploy";git config --global user.name "Travis deployment";
- git remote set-branches --add origin gh-pages; 
- git fetch --all ; 
- git checkout gh-pages; 
- gulp build:gh-pages;
cache:
  directories:
  - node_modules
  - bower_components
  
